--// Special Events \\--
return {
    Names = {
        "FischFright",
        "Mossjaw Hunt",
        
        "Beluga",
        "Apex Leviathan",
        "Bloop Fish",
        "Cosmic Relic",
        "Earthquake",
        "Emoji Fishes",

        "Colossal Blue Dragon",
        "Colossal Ancient Dragon",
        "Colossal Ethereal Dragon",

        "Mosslurker",
        "Narwhal",
        "Magician Narwhal",
        "Bloop Fish",

        "Blue Moon Pool",

        "Whales Pool",
        "Forsaken Veil - Scylla",
        
        "Orcas Pool",
        "Ancient Orcas Pool",

        "Megalodon Default",
        "Megalodon Ancient",
        "Birthday Megalodon",

        "Whale Shark",
        "Great Hammerhead Shark",
        "Great White Shark",

        "The Kraken Pool",
        "Ancient Kraken Pool",

        "Isonade"
    },

    IsAbundance = {

    },

    SpecialChecks = {
        ["Mossjaw Hunt"] = 1,
    },

    Aliases = {
        ["FischFright"]         = { "FischFright", "FischFright25" },
        ["Emoji Fishes"]        = { "EmojiFish" },
        ["Cosmic Relic"]        = { "CosmicRelic" },
        ["Beluga"]              = { "Beluga - Sea 1", "Beluga - Sea 2" },
        ["Narwhal"]             = { "Narwhal - Sea 1", "Narwhal - Sea 2" },
        ["Magician Narwhal"]    = { "Magician Narwhal - Sea 1", "Magician Narwhal - Sea 2" },
        ["Blue Moon Pool"]      = { "Blue Moon Pool", "Blue Moon - First Sea" }
    }
}
