return {
    --// NPCs \\--
    NPCs = {
        Anglers = {
            "LostJungleAngler",
            "The Depths Angler",
            "Ancient Isle Angler",
            "Forsaken Shores Angler",
            "Roslit Angler",
            "Terrapin Angler",
            "Sunstone Angler",
            "Moosewood Angler",
        },

        Shipwrights = {
            "Forsaken Shipwright",
            "Statue Shipwright",
            "Moosewood Shipwright",
            "Sunstone Shipwright",
            "Snowcap Shipwright",
            "Terrapin Shipwright",
            "Roslit Shipwright",
            "Castaway Cliffs Shipwright",
            "Ancient Shipwright",
            "Laboratory Shipwright",
            "Summit Shipwright",
            "Gramd Reef Shipwright",
            "Mushgrove Shipwright",
        }
    },

    --// Special Events \\--
    SpecialEvents = {
        Names = {
            "FischFright",
            "Mossjaw Hunt",
            
            "Beluga",
            "Apex Leviathan",
            "Bloop Fish",
            "Cosmic Relic",
            "Earthquake",
            "Emoji Fishes",

            "Colossal Blue Dragon",
            "Colossal Ancient Dragon",
            "Colossal Ethereal Dragon",

            "Mosslurker",
            "Narwhal",
            "Magician Narwhal",
            "Bloop Fish",

            "Blue Moon Pool",

            "Whales Pool",
            "Forsaken Veil - Scylla",
            
            "Orcas Pool",
            "Ancient Orcas Pool",

            "Megalodon Default",
            "Megalodon Ancient",
            "Birthday Megalodon",

            "Whale Shark",
            "Great Hammerhead Shark",
            "Great White Shark",

            "The Kraken Pool",
            "Ancient Kraken Pool",

            "Isonade"
        },

        IsAbundance = {

        },

        SpecialChecks = {

        },

        Aliases = {
            ["FischFright"]         = { "FischFright", "FischFright25" },
            ["Emoji Fishes"]        = { "EmojiFish" },
            ["Cosmic Relic"]        = { "CosmicRelic" },
            ["Beluga"]              = { "Beluga - Sea 1", "Beluga - Sea 2" },
            ["Narwhal"]             = { "Narwhal - Sea 1", "Narwhal - Sea 2" },
            ["Magician Narwhal"]    = { "Magician Narwhal - Sea 1", "Magician Narwhal - Sea 2" },
            ["Blue Moon Pool"]      = { "Blue Moon Pool", "Blue Moon - First Sea" }
        }
    },

    --// Zones \\--
    Zones = {
        Aliases = {
            ["Veil of the Forsaken"]    = "Forsaken Veil",
            ["Challenger's Deep"]       = "Challengers Deep"
        }
    }
}
