return {
    Magnet = {
        LureSpeed = 0,
        Luck = 200,
        GenerelLuck = 0,
        Rarity = "Unusual",
        Resilience = 0
    },
    Worm = {
        LureSpeed = 15,
        Luck = 25,
        GenerelLuck = 0,
        Rarity = "Common",
        Resilience = 0
    },
    ["Peppermint Worm"] = {
        LureSpeed = -5,
        Luck = 50,
        GenerelLuck = 30,
        Rarity = "Unusual",
        Resilience = 20
    },
    Coal = {
        LureSpeed = 0,
        Luck = 45,
        GenerelLuck = 0,
        Rarity = "Rare",
        Resilience = -10
    },
    Squid = {
        LureSpeed = -25,
        Luck = 55,
        GenerelLuck = 45,
        Rarity = "Unusual",
        Resilience = 0
    },
    Shrimp = {
        LureSpeed = 0,
        Luck = 45,
        GenerelLuck = 25,
        Rarity = "Uncommon",
        Resilience = -5
    },
    Give = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    ["Kraken Tentacle"] = {
        LureSpeed = 35,
        Luck = 100,
        GenerelLuck = 35,
        Rarity = "Legendary",
        Resilience = 15
    },
    ["Hangman's Hook"] = {
        ProgressSpeed = 45,
        LureSpeed = -5,
        Luck = 150,
        GenerelLuck = 35,
        Rarity = "Mythical",
        Resilience = 20
    },
    Insect = {
        LureSpeed = 5,
        Luck = 35,
        GenerelLuck = 0,
        Rarity = "Common",
        Resilience = 0
    },
    ["Night Shrimp"] = {
        LureSpeed = 15,
        Luck = 0,
        GenerelLuck = 90,
        Rarity = "Legendary",
        Resilience = 0
    },
    ["Deep Coral"] = {
        LureSpeed = 0,
        Luck = -10,
        GenerelLuck = 0,
        Rarity = "Legendary",
        Resilience = 50
    },
    ["Chocolate Fish"] = {
        LureSpeed = 20,
        Luck = 200,
        Rarity = "Mythical",
        Mutation = "Chocolate",
        GenerelLuck = 150,
        Resilience = 15
    },
    ["Super Flakes"] = {
        LureSpeed = 0,
        Luck = 0,
        GenerelLuck = 70,
        Rarity = "Rare",
        Resilience = -15
    },
    Seaweed = {
        LureSpeed = 20,
        Luck = 35,
        GenerelLuck = 0,
        Rarity = "Unusual",
        Resilience = 10
    },
    ["Instant Catcher"] = {
        LureSpeed = 65,
        Luck = 0,
        GenerelLuck = -20,
        Rarity = "Legendary",
        Resilience = -15
    },
    ["Shark Head"] = {
        LureSpeed = -5,
        Luck = 225,
        GenerelLuck = 30,
        Rarity = "Mythical",
        Resilience = 10
    },
    ["Fish Head"] = {
        LureSpeed = 10,
        Luck = 150,
        GenerelLuck = 0,
        Rarity = "Legendary",
        Resilience = -10
    },
    ["Weird Algae"] = {
        LureSpeed = -35,
        Luck = 0,
        GenerelLuck = 200,
        Rarity = "Legendary",
        Resilience = 0
    },
    Garbage = {
        LureSpeed = -5,
        Luck = 0,
        GenerelLuck = -250,
        Rarity = "Common",
        Resilience = 50
    },
    ["Holly Berry"] = {
        LureSpeed = -5,
        Luck = 80,
        GenerelLuck = 30,
        Rarity = "Legendary",
        Resilience = 10
    },
    ["Rapid Catcher"] = {
        LureSpeed = 35,
        Luck = 0,
        GenerelLuck = 0,
        Rarity = "Rare",
        Resilience = -15
    },
    Minnow = {
        LureSpeed = 0,
        Luck = 65,
        GenerelLuck = 0,
        Rarity = "Unusual",
        Resilience = -10
    },
    Maggot = {
        LureSpeed = -10,
        Luck = 0,
        GenerelLuck = 35,
        Rarity = "Uncommon",
        Resilience = 0
    },
    Coral = {
        LureSpeed = 20,
        Luck = 0,
        GenerelLuck = 0,
        Rarity = "Unusual",
        Resilience = 20
    },
    Flakes = {
        LureSpeed = 10,
        Luck = 55,
        GenerelLuck = 0,
        Rarity = "Common",
        Resilience = -3
    },
    ["Aurora Bait"] = {
        LureSpeed = -5,
        Luck = 100,
        GenerelLuck = 30,
        Rarity = "Mythical",
        Resilience = 10
    },
    Bagel = {
        LureSpeed = 0,
        Luck = 25,
        GenerelLuck = 0,
        Rarity = "Common",
        Resilience = 15
    },
    ["Truffle Worm"] = {
        LureSpeed = -10,
        Luck = 300,
        GenerelLuck = 0,
        Rarity = "Legendary",
        Resilience = 0
    }
}