return {
    ["Glass Beetle"] = {
        LureSpeed = 30,
        Luck = 125,
        Rarity = "Rare",
        GenerelLuck = -80,
        Icon = "rbxassetid://108650710805383",
        Resilience = 30
    },
    Worm = {
        LureSpeed = 15,
        Luck = 25,
        Rarity = "Common",
        GenerelLuck = 0,
        Icon = "rbxassetid://133997443467885",
        Resilience = 0
    },
    ["Golden Tentacle"] = {
        LureSpeed = 50,
        Luck = 150,
        Limited = true,
        Rarity = "Legendary",
        GenerelLuck = 40,
        Icon = "rbxassetid://83405723534819",
        Resilience = 20
    },
    ["Peppermint Worm"] = {
        Limited = true,
        LureSpeed = -5,
        Luck = 50,
        Rarity = "Unusual",
        Resilience = 20,
        GenerelLuck = 30,
        Icon = "rbxassetid://93911511219039",
        DontGiveToANewAccount = true
    },
    Squid = {
        LureSpeed = -25,
        Luck = 55,
        Rarity = "Unusual",
        GenerelLuck = 45,
        Icon = "rbxassetid://132083884054870",
        Resilience = 0
    },
    ["Fish Head"] = {
        LureSpeed = 10,
        Luck = 150,
        Rarity = "Legendary",
        GenerelLuck = 0,
        Icon = "rbxassetid://82318594895677",
        Resilience = -10
    },
    ["Ember Berries"] = {
        LureSpeed = 5,
        Luck = 120,
        Rarity = "Unusual",
        GenerelLuck = 45,
        Icon = "rbxassetid://106591280919281",
        Resilience = 15
    },
    Insect = {
        LureSpeed = 5,
        Luck = 35,
        Rarity = "Common",
        GenerelLuck = 0,
        Icon = "rbxassetid://82228384077490",
        Resilience = 0
    },
    ["Crystal Bananas"] = {
        LureSpeed = 0,
        Luck = 150,
        Rarity = "Rare",
        GenerelLuck = 90,
        Icon = "rbxassetid://132112236254457",
        Resilience = 25
    },
    ["Toxic Jelly Core"] = {
        LureSpeed = -5,
        Luck = 180,
        Rarity = "Legendary",
        GenerelLuck = 90,
        Icon = "rbxassetid://103314073936320",
        Resilience = 35
    },
    ["Hangman's Hook"] = {
        ProgressSpeed = 45,
        LureSpeed = -5,
        Luck = 150,
        Rarity = "Mythical",
        GenerelLuck = 35,
        Icon = "rbxassetid://129988917083814",
        Resilience = 20
    },
    ["Super Flakes"] = {
        LureSpeed = 0,
        Luck = 0,
        Rarity = "Rare",
        GenerelLuck = 70,
        Icon = "rbxassetid://105233590701549",
        Resilience = -15
    },
    ["Nightmare Larva"] = {
        LureSpeed = 25,
        Luck = 120,
        Rarity = "Mythical",
        GenerelLuck = 35,
        Icon = "rbxassetid://139717203005579",
        Resilience = 25
    },
    ["Weird Algae"] = {
        LureSpeed = -35,
        Luck = 0,
        Rarity = "Legendary",
        GenerelLuck = 200,
        Icon = "rbxassetid://100508147066133",
        Resilience = 0
    },
    ["Shark Head"] = {
        LureSpeed = -5,
        Luck = 225,
        Rarity = "Mythical",
        GenerelLuck = 30,
        Icon = "rbxassetid://134025031777629",
        Resilience = 10
    },
    ["Phantom Leech"] = {
        LureSpeed = 10,
        Luck = 55,
        Rarity = "Rare",
        GenerelLuck = 30,
        Icon = "rbxassetid://123505973177484",
        Resilience = 25
    },
    ["Deep Coral"] = {
        LureSpeed = 0,
        Luck = -10,
        Rarity = "Legendary",
        GenerelLuck = 0,
        Icon = "rbxassetid://71969712298871",
        Resilience = 50
    },
    ["Aurora Bait"] = {
        LureSpeed = -5,
        Luck = 100,
        Limited = true,
        Rarity = "Mythical",
        GenerelLuck = 30,
        Icon = "rbxassetid://85141818620239",
        Resilience = 10
    },
    Bagel = {
        LureSpeed = 0,
        Luck = 25,
        Rarity = "Common",
        GenerelLuck = 0,
        Icon = "rbxassetid://108678002533415",
        Resilience = 15
    },
    Give = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    Magnet = {
        LureSpeed = 0,
        Luck = 200,
        Rarity = "Unusual",
        GenerelLuck = 0,
        Icon = "rbxassetid://127635918006645",
        Resilience = 0
    },
    ["Whale Bait"] = {
        LureSpeed = -5,
        Luck = 180,
        Rarity = "Legendary",
        Price = 800,
        GenerelLuck = 20,
        Icon = "rbxassetid://76695597473114",
        Resilience = 30
    },
    ["Golden Shrimp Bait"] = {
        LureSpeed = 15,
        Luck = 120,
        Rarity = "Mythical",
        Price = 1500,
        GenerelLuck = 90,
        Icon = "rbxassetid://101398702799761",
        Resilience = 10
    },
    ["Hourglass Bait"] = {
        Rarity = "Mythical",
        Limited = true,
        XpBoost = 1,
        LureSpeed = 5,
        Luck = 150,
        Mutation = "Neon",
        GenerelLuck = 150,
        Icon = "rbxassetid://136590369641722",
        Resilience = 40
    },
    ["Neuro Slug"] = {
        LureSpeed = -20,
        Luck = 90,
        Rarity = "Legendary",
        GenerelLuck = 100,
        Icon = "rbxassetid://98378589712685",
        Resilience = 60
    },
    Coal = {
        LureSpeed = 0,
        Luck = 45,
        Rarity = "Rare",
        GenerelLuck = 0,
        Icon = "rbxassetid://128813695014519",
        Resilience = -10
    },
    ["Colossal Ink Bait"] = {
        Mutation = "Colossal Ink",
        LureSpeed = 5,
        Luck = 150,
        Limited = true,
        Rarity = "Mythical",
        GenerelLuck = 150,
        Icon = "rbxassetid://78817927104320",
        Resilience = 40
    },
    Shrimp = {
        LureSpeed = 0,
        Luck = 45,
        Rarity = "Uncommon",
        GenerelLuck = 25,
        Icon = "rbxassetid://129458957024181",
        Resilience = -5
    },
    ["Stud Bait"] = {
        LureSpeed = 50,
        Luck = 150,
        Limited = true,
        Rarity = "Legendary",
        GenerelLuck = 40,
        Icon = "rbxassetid://92827044886722",
        Resilience = 20
    },
    ["Luminous Larva"] = {
        LureSpeed = 10,
        Luck = 200,
        Rarity = "Exotic",
        GenerelLuck = 175,
        Icon = "rbxassetid://98270395522373",
        Resilience = 50
    },
    ["Gale Grub"] = {
        LureSpeed = 30,
        Luck = 75,
        Rarity = "Common",
        GenerelLuck = -10,
        Icon = "rbxassetid://89278213759164",
        Resilience = -5
    },
    Coral = {
        LureSpeed = 20,
        Luck = 0,
        Rarity = "Unusual",
        GenerelLuck = 0,
        Icon = "rbxassetid://88295442439044",
        Resilience = 20
    },
    ["Sapphire Krill"] = {
        LureSpeed = 5,
        Luck = 150,
        Rarity = "Mythical",
        GenerelLuck = 150,
        Icon = "rbxassetid://105153897307029",
        Resilience = 40
    },
    ["Lagoon Leech"] = {
        LureSpeed = 15,
        Luck = 65,
        Rarity = "Rare",
        GenerelLuck = -10,
        Icon = "rbxassetid://131228054836930",
        Resilience = 20
    },
    ["Chocolate Fish"] = {
        Limited = true,
        LureSpeed = 20,
        Luck = 200,
        Rarity = "Mythical",
        GenerelLuck = 150,
        Mutation = "Chocolate",
        Icon = "rbxassetid://122149688355947",
        Resilience = 15
    },
    ["Night Shrimp"] = {
        LureSpeed = 15,
        Luck = 0,
        Rarity = "Legendary",
        GenerelLuck = 90,
        Icon = "rbxassetid://93937013256967",
        Resilience = 0
    },
    Lushrooms = {
        LureSpeed = 10,
        Luck = 50,
        Rarity = "Common",
        GenerelLuck = 20,
        Icon = "rbxassetid://96329947106909",
        Resilience = 10
    },
    ["Instant Catcher"] = {
        LureSpeed = 65,
        Luck = 0,
        Rarity = "Legendary",
        GenerelLuck = -20,
        Icon = "rbxassetid://105765233417193",
        Resilience = -15
    },
    Snare = {
        LureSpeed = 80,
        Luck = 125,
        XpBoost = 1,
        Rarity = "Secret",
        GenerelLuck = -10,
        Icon = "rbxassetid://131502303758768",
        Resilience = -20
    },
    ["Mist Worms"] = {
        LureSpeed = 20,
        Luck = 100,
        Rarity = "Legendary",
        GenerelLuck = 80,
        Icon = "rbxassetid://75993334361705",
        Resilience = 25
    },
    ["Kraken Tentacle"] = {
        LureSpeed = 35,
        Luck = 100,
        Rarity = "Legendary",
        GenerelLuck = 35,
        Icon = "rbxassetid://81433219929632",
        Resilience = 15
    },
    Garbage = {
        LureSpeed = -5,
        Luck = 0,
        Rarity = "Common",
        GenerelLuck = -250,
        Icon = "rbxassetid://134913713768472",
        Resilience = 50
    },
    ["Holly Berry"] = {
        Limited = true,
        LureSpeed = -5,
        Luck = 80,
        Rarity = "Legendary",
        Resilience = 10,
        GenerelLuck = 30,
        Icon = "rbxassetid://78831863135519",
        DontGiveToANewAccount = true
    },
    ["Rapid Catcher"] = {
        LureSpeed = 35,
        Luck = 0,
        Rarity = "Rare",
        GenerelLuck = 0,
        Icon = "rbxassetid://123038194837270",
        Resilience = -15
    },
    Minnow = {
        LureSpeed = 0,
        Luck = 65,
        Rarity = "Unusual",
        GenerelLuck = 0,
        Icon = "rbxassetid://127324539778135",
        Resilience = -10
    },
    Maggot = {
        LureSpeed = -10,
        Luck = 0,
        Rarity = "Uncommon",
        GenerelLuck = 35,
        Icon = "rbxassetid://77502257509358",
        Resilience = 0
    },
    ["Golden Worm"] = {
        LureSpeed = 20,
        Luck = 200,
        Rarity = "Exotic",
        GenerelLuck = 100,
        Icon = "rbxassetid://92588934474259",
        Resilience = 45
    },
    Flakes = {
        LureSpeed = 10,
        Luck = 55,
        Rarity = "Common",
        GenerelLuck = 0,
        Icon = "rbxassetid://89483992302592",
        Resilience = -3
    },
    Seaweed = {
        LureSpeed = 20,
        Luck = 35,
        Rarity = "Unusual",
        GenerelLuck = 0,
        Icon = "rbxassetid://78676762283786",
        Resilience = 10
    },
    Lucky = {
        Rarity = "Mythical",
        Limited = true,
        MutationChance = {
            1,
            100,
            50
        },
        LureSpeed = 20,
        Luck = 200,
        GenerelLuck = 150,
        Mutation = "Blarney",
        Icon = "rbxassetid://83124206397968",
        Resilience = 15
    },
    ["Truffle Worm"] = {
        LureSpeed = -10,
        Luck = 300,
        Rarity = "Legendary",
        GenerelLuck = 0,
        Icon = "rbxassetid://93019675927218",
        Resilience = 0
    }
}