return {
    Lucky = {
        MutationChance = {
            1,
            100,
            50
        },
        LureSpeed = 20,
        Luck = 200,
        Rarity = "Mythical",
        GenerelLuck = 150,
        Mutation = "Blarney",
        Icon = "rbxassetid://83124206397968",
        Resilience = 15
    },
    Worm = {
        LureSpeed = 15,
        Luck = 25,
        Rarity = "Common",
        GenerelLuck = 0,
        Icon = "rbxassetid://133997443467885",
        Resilience = 0
    },
    Give = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    ["Golden Tentacle"] = {
        LureSpeed = 50,
        Luck = 150,
        Rarity = "Legendary",
        GenerelLuck = 40,
        Icon = "rbxassetid://83405723534819",
        Resilience = 20
    },
    ["Peppermint Worm"] = {
        LureSpeed = -5,
        Luck = 50,
        Rarity = "Unusual",
        Resilience = 20,
        GenerelLuck = 30,
        Icon = "rbxassetid://93911511219039",
        DontGiveToANewAccount = true
    },
    Coal = {
        LureSpeed = 0,
        Luck = 45,
        Rarity = "Rare",
        GenerelLuck = 0,
        Icon = "rbxassetid://128813695014519",
        Resilience = -10
    },
    Squid = {
        LureSpeed = -25,
        Luck = 55,
        Rarity = "Unusual",
        GenerelLuck = 45,
        Icon = "rbxassetid://132083884054870",
        Resilience = 0
    },
    Shrimp = {
        LureSpeed = 0,
        Luck = 45,
        Rarity = "Uncommon",
        GenerelLuck = 25,
        Icon = "rbxassetid://129458957024181",
        Resilience = -5
    },
    ["Kraken Tentacle"] = {
        LureSpeed = 35,
        Luck = 100,
        Rarity = "Legendary",
        GenerelLuck = 35,
        Icon = "rbxassetid://81433219929632",
        Resilience = 15
    },
    ["Hangman's Hook"] = {
        ProgressSpeed = 45,
        LureSpeed = -5,
        Luck = 150,
        Rarity = "Mythical",
        GenerelLuck = 35,
        Icon = "rbxassetid://129988917083814",
        Resilience = 20
    },
    ["Rapid Catcher"] = {
        LureSpeed = 35,
        Luck = 0,
        Rarity = "Rare",
        GenerelLuck = 0,
        Icon = "rbxassetid://123038194837270",
        Resilience = -15
    },
    Insect = {
        LureSpeed = 5,
        Luck = 35,
        Rarity = "Common",
        GenerelLuck = 0,
        Icon = "rbxassetid://82228384077490",
        Resilience = 0
    },
    ["Deep Coral"] = {
        LureSpeed = 0,
        Luck = -10,
        Rarity = "Legendary",
        GenerelLuck = 0,
        Icon = "rbxassetid://71969712298871",
        Resilience = 50
    },
    ["Shark Head"] = {
        LureSpeed = -5,
        Luck = 225,
        Rarity = "Mythical",
        GenerelLuck = 30,
        Icon = "rbxassetid://134025031777629",
        Resilience = 10
    },
    ["Chocolate Fish"] = {
        LureSpeed = 20,
        Luck = 200,
        Rarity = "Mythical",
        GenerelLuck = 150,
        Mutation = "Chocolate",
        Icon = "rbxassetid://122149688355947",
        Resilience = 15
    },
    ["Super Flakes"] = {
        LureSpeed = 0,
        Luck = 0,
        Rarity = "Rare",
        GenerelLuck = 70,
        Icon = "rbxassetid://105233590701549",
        Resilience = -15
    },
    Seaweed = {
        LureSpeed = 20,
        Luck = 35,
        Rarity = "Unusual",
        GenerelLuck = 0,
        Icon = "rbxassetid://78676762283786",
        Resilience = 10
    },
    ["Instant Catcher"] = {
        LureSpeed = 65,
        Luck = 0,
        Rarity = "Legendary",
        GenerelLuck = -20,
        Icon = "rbxassetid://105765233417193",
        Resilience = -15
    },
    ["Night Shrimp"] = {
        LureSpeed = 15,
        Luck = 0,
        Rarity = "Legendary",
        GenerelLuck = 90,
        Icon = "rbxassetid://93937013256967",
        Resilience = 0
    },
    ["Fish Head"] = {
        LureSpeed = 10,
        Luck = 150,
        Rarity = "Legendary",
        GenerelLuck = 0,
        Icon = "rbxassetid://82318594895677",
        Resilience = -10
    },
    ["Weird Algae"] = {
        LureSpeed = -35,
        Luck = 0,
        Rarity = "Legendary",
        GenerelLuck = 200,
        Icon = "rbxassetid://100508147066133",
        Resilience = 0
    },
    Garbage = {
        LureSpeed = -5,
        Luck = 0,
        Rarity = "Common",
        GenerelLuck = -250,
        Icon = "rbxassetid://134913713768472",
        Resilience = 50
    },
    ["Holly Berry"] = {
        LureSpeed = -5,
        Luck = 80,
        Rarity = "Legendary",
        Resilience = 10,
        GenerelLuck = 30,
        Icon = "rbxassetid://78831863135519",
        DontGiveToANewAccount = true
    },
    Minnow = {
        LureSpeed = 0,
        Luck = 65,
        Rarity = "Unusual",
        GenerelLuck = 0,
        Icon = "rbxassetid://127324539778135",
        Resilience = -10
    },
    Coral = {
        LureSpeed = 20,
        Luck = 0,
        Rarity = "Unusual",
        GenerelLuck = 0,
        Icon = "rbxassetid://88295442439044",
        Resilience = 20
    },
    Maggot = {
        LureSpeed = -10,
        Luck = 0,
        Rarity = "Uncommon",
        GenerelLuck = 35,
        Icon = "rbxassetid://77502257509358",
        Resilience = 0
    },
    Magnet = {
        LureSpeed = 0,
        Luck = 200,
        Rarity = "Unusual",
        GenerelLuck = 0,
        Icon = "rbxassetid://127635918006645",
        Resilience = 0
    },
    Flakes = {
        LureSpeed = 10,
        Luck = 55,
        Rarity = "Common",
        GenerelLuck = 0,
        Icon = "rbxassetid://89483992302592",
        Resilience = -3
    },
    ["Aurora Bait"] = {
        LureSpeed = -5,
        Luck = 100,
        Rarity = "Mythical",
        GenerelLuck = 30,
        Icon = "rbxassetid://85141818620239",
        Resilience = 10
    },
    Bagel = {
        LureSpeed = 0,
        Luck = 25,
        Rarity = "Common",
        GenerelLuck = 0,
        Icon = "rbxassetid://108678002533415",
        Resilience = 15
    },
    ["Truffle Worm"] = {
        LureSpeed = -10,
        Luck = 300,
        Rarity = "Legendary",
        GenerelLuck = 0,
        Icon = "rbxassetid://93019675927218",
        Resilience = 0
    }
}