return {
    Enchants = {
        ["Sea King"] = {
            StatIncrease = 35,
            Description = "Makes fish 35% bigger",
            Color = Color3.new(0.20784313976765, 0.30196079611778, 0.82745099067688),
            Display = "Sea King",
            IsExalted = false,
            StrokeColor = Color3.new(0.035294119268656, 0.050980392843485, 0.13725490868092)
        },
        Lucky = {
            StatIncrease = 20,
            Description = "Increases Luck by 20%, Lure Speed by 15%, & natural Mutation chances by 40%",
            Display = "Lucky",
            Color = Color3.new(0.49411764740944, 0.89803922176361, 0.64313727617264),
            MutationStatIncrease = 40,
            IsExalted = false,
            StrokeColor = Color3.new(0.098039217293262, 0.17647059261799, 0.12549020349979)
        },
        Scrapper = {
            StatIncrease = 60,
            Description = "60% chance to not consume Bait",
            Color = Color3.new(1, 0.60784316062927, 0.32549020648003),
            Display = "Scrapper",
            IsExalted = false,
            StrokeColor = Color3.new(0.14117647707462, 0.090196080505848, 0.050980392843485)
        },
        Divine = {
            StatIncrease = 45,
            Description = "Increases luck by 45%, Resilience by 20%, & Lure Speed by 20%",
            Color = Color3.new(0.77647060155869, 0.89803922176361, 0.86274510622025),
            Display = "Divine",
            IsExalted = false,
            StrokeColor = Color3.new(0.46274510025978, 0.52941179275513, 0.51764708757401)
        },
        ["Blessed Song"] = {
            StatIncrease = 40,
            Description = "Increases Progress Speed by 40%",
            IsSongOfTheDeep = true,
            Color = Color3.new(0, 0.66666668653488, 1),
            Display = "Blessed Song",
            ProgressSpeedBoost = 40,
            StrokeColor = Color3.new(0, 0.2352941185236, 0.35294118523598)
        },
        Steady = {
            StatIncrease = 20,
            Description = "Increases Progress Speed by 20%",
            IsExalted = false,
            Color = Color3.new(0.89803922176361, 0.81176471710205, 0.74901962280273),
            Display = "Steady",
            ProgressSpeedBoost = 20,
            StrokeColor = Color3.new(0.082352943718433, 0.074509806931019, 0.070588238537312)
        },
        Noir = {
            StatIncrease = 100,
            Description = "Caught fish will be Albino or Darkened, with a slight size boost",
            WeightIncrease = 10,
            Color = Color3.new(1, 1, 1),
            Display = "Noir",
            IsExalted = false,
            StrokeColor = Color3.new(0, 0, 0)
        },
        Abyssal = {
            StatIncrease = 10,
            Description = "Caught fish have a 10% chance to be Abyssal, & a chance to be larger, or a low chance to be notably smaller",
            Color = Color3.new(0.15294118225574, 0.22352941334248, 0.678431391716),
            Display = "Abyssal",
            IsExalted = false,
            StrokeColor = Color3.new(0.32549020648003, 0.16078431904316, 0.678431391716)
        },
        Mutated = {
            StatIncrease = 90,
            Description = "Increases natural Mutation chances by 90%",
            Color = Color3.new(0.57647061347961, 0.89803922176361, 0.43921568989754),
            Display = "Mutated",
            IsExalted = false,
            StrokeColor = Color3.new(0.17647059261799, 0.22745098173618, 0.15294118225574)
        },
        Unbreakable = {
            StatIncrease = 10000,
            Description = "Increases Strength by 10,000kg, & Control by 0.1",
            Display = "Unbreakable",
            Color = Color3.new(0.88235294818878, 0.70196080207825, 0.89803922176361),
            ControlIncrease = 0.1,
            IsExalted = false,
            StrokeColor = Color3.new(0.062745101749897, 0.050980392843485, 0.062745101749897)
        },
        Piercing = {
            StatIncrease = 0,
            Description = "Rod has a chance to stab fish while reeling, & increases Progress Speed by 15%",
            IsExalted = true,
            Color = Color3.new(0.050980392843485, 0.65490198135376, 0.55294120311737),
            Display = "Piercing",
            ProgressSpeedBoost = 15,
            StrokeColor = Color3.new(0.011764706112444, 0.15686275064945, 0.1294117718935)
        },
        Storming = {
            StatIncrease = 95,
            Display = "Storming",
            Description = "During a rainy day, Luck is increased by 95%, Lure Speed by 45%, & grants a 50% chance for caught fish to be Electric",
            LureSpeedBonus = 45,
            Color = Color3.new(1, 0.92549020051956, 0.5137255191803),
            ElectricMutationChance = 50,
            IsExalted = false,
            StrokeColor = Color3.new(0.14117647707462, 0.14117647707462, 0.094117648899555)
        },
        Chronos = {
            StatIncrease = 0,
            Description = "Occasionally freeze fish in place",
            Color = Color3.new(0.11372549086809, 0.32941177487373, 0.82745099067688),
            Worlds = {
                "Sea 2"
            },
            Display = "Chronos",
            StrokeColor = Color3.new(0.04313725605607, 0.050980392843485, 0.13725490868092)
        },
        Clever = {
            StatIncrease = 2.25,
            Description = "2.25X XP after catching a fish",
            Color = Color3.new(1, 0.43137255311012, 0.65098041296005),
            Display = "Clever",
            IsExalted = false,
            StrokeColor = Color3.new(0.14117647707462, 0.070588238537312, 0.094117648899555)
        },
        Anomalous = {
            StatIncrease = 0,
            Description = "Caught fish have a 20% chance to be duplicated & Anomalous",
            Color = Color3.new(1, 0.11372549086809, 0.11372549086809),
            Display = "Anomalous",
            IsExalted = true,
            StrokeColor = Color3.new(0.13725490868092, 0.015686275437474, 0.015686275437474)
        },
        Invincible = {
            StatIncrease = math.huge,
            Description = "Grants infinite Strength, & allows fishing in any body of liquid",
            Color = Color3.new(1, 0.38431373238564, 0.098039217293262),
            Display = "Invincible",
            IsExalted = true,
            StrokeColor = Color3.new(0.13725490868092, 0.050980392843485, 0.011764706112444)
        },
        Long = {
            StatIncrease = 50,
            Description = "Increases Line Distance by 50 studs, Resilience by 20%, & Progress Speed by 5%",
            IsExalted = false,
            Color = Color3.new(0.87450981140137, 0.64705884456635, 0.25098040699959),
            Display = "Long",
            ProgressSpeedBoost = 5,
            StrokeColor = Color3.new(0.1294117718935, 0.098039217293262, 0.054901961237192)
        },
        Swift = {
            StatIncrease = 30,
            Description = "Increases Lure Speed by 30%, & Progress Speed by 5%",
            IsExalted = false,
            Color = Color3.new(0.70980393886566, 0.8901960849762, 0.89803922176361),
            Display = "Swift",
            ProgressSpeedBoost = 5,
            StrokeColor = Color3.new(0.15686275064945, 0.19607843458652, 0.19607843458652)
        },
        Mystical = {
            StatIncrease = 45,
            IsExalted = true,
            Description = "Increases Luck by 25%, Resilience by 45%, Lure Speed by 15%, & Progress Speed by 10%",
            LuckStatIncrease = 25,
            Color = Color3.new(0.76078432798386, 0.87450981140137, 1),
            Display = "Mystical",
            ProgressSpeedBoost = 10,
            StrokeColor = Color3.new(0.16862745583057, 0.19607843458652, 0.22352941334248)
        },
        Wormhole = {
            StatIncrease = 80,
            Description = "80% chance to catch a fish from a random place",
            Color = Color3.new(0.5686274766922, 0.35294118523598, 1),
            Display = "Wormhole",
            IsExalted = false,
            StrokeColor = Color3.new(0.050980392843485, 0.031372550874949, 0.086274512112141)
        },
        ["Blood Reckoning"] = {
            StatIncrease = 0,
            Description = "Sacrifice health for a health-dependent chance to apply the Sanguine mutation",
            Worlds = {
                "Sea 2"
            },
            Color = Color3.new(0.29019609093666, 0.031372550874949, 0.031372550874949),
            HealthCost = 30,
            Display = "Blood Reckoning",
            StrokeColor = Color3.new(0.63921570777893, 0.066666670143604, 0.066666670143604)
        },
        Controlled = {
            StatIncrease = 0.15,
            Description = "Increases Control by 0.15",
            Color = Color3.new(0.68627452850342, 0.60784316062927, 1),
            Display = "Controlled",
            IsExalted = false,
            StrokeColor = Color3.new(0.12549020349979, 0.10980392247438, 0.15294118225574)
        },
        Momentum = {
            StatIncrease = 0,
            Description = "Perfect Catches increase Lure, Resilience & Progress Speed incrementally",
            Worlds = {
                "Sea 2"
            },
            Color = Color3.new(0.82745099067688, 0.70196080207825, 0.50196081399918),
            Display = "Momentum",
            ProgressSpeedBoost = 0,
            StrokeColor = Color3.new(0.13725490868092, 0.10588235408068, 0.070588238537312)
        },
        Chaotic = {
            StatIncrease = 8,
            Description = "Unleash pure chaos with every cast. Slashes fish with an 8% chance to awaken the Chaotic mutation",
            Color = Color3.new(0.078431375324726, 0.074509806931019, 0.086274512112141),
            Worlds = {
                "Sea 2"
            },
            Display = "Chaotic",
            StrokeColor = Color3.new(1, 1, 1)
        },
        Scavenger = {
            StatIncrease = 0,
            Description = "Raised chances for utility catches",
            Color = Color3.new(1, 0.74901962280273, 0.40000000596046),
            Worlds = {
                "Sea 2"
            },
            Display = "Scavenger",
            StrokeColor = Color3.new(0.21960784494877, 0.15294118225574, 0.050980392843485)
        },
        Insight = {
            StatIncrease = 1.5,
            Description = "1.5X XP after catching a fish, Lure Speed increased by 20%, & grants a 30% chance to Purify caught fish",
            Display = "Insight",
            Color = Color3.new(0.50196081399918, 1, 0.44705882668495),
            PurifiedChance = 30,
            IsExalted = false,
            StrokeColor = Color3.new(0.11372549086809, 0.14117647707462, 0.10588235408068)
        },
        Flashline = {
            StatIncrease = 0,
            Worlds = {
                "Sea 2"
            },
            Description = "A small chance of majorly boosted Progress Speed",
            AltProgressSpeedBoost = 10,
            Color = Color3.new(1, 1, 1),
            Display = "Flashline",
            ProgressSpeedBoost = 80,
            StrokeColor = Color3.new(0.19215686619282, 0.19215686619282, 0.19215686619282)
        },
        Immortal = {
            StatIncrease = 75,
            Description = "Increases Luck by 75%, & Progress Speed by 30%",
            IsExalted = true,
            Color = Color3.new(0.90980392694473, 0.85098040103912, 1),
            Display = "Immortal",
            ProgressSpeedBoost = 30,
            StrokeColor = Color3.new(0.27058824896812, 0.2549019753933, 0.29803922772408)
        },
        ["Sea Overlord"] = {
            StatIncrease = 50,
            Description = "Makes fish 50% bigger",
            Color = Color3.new(0.20000000298023, 0.65882354974747, 0.82745099067688),
            Display = "Sea Overlord",
            IsExalted = true,
            StrokeColor = Color3.new(0.035294119268656, 0.11372549086809, 0.13725490868092)
        },
        Quantum = {
            StatIncrease = 25,
            Description = "Caught fish have a 25% chance to be Subspace",
            Color = Color3.new(1, 0, 0.70196080207825),
            Display = "Quantum",
            IsExalted = true,
            StrokeColor = Color3.new(0.19215686619282, 0, 0.14117647707462)
        },
        Herculean = {
            StatIncrease = 25000,
            IsExalted = true,
            Description = "Increases Strength by 25,000kg, Control by 0.2, & Progress Speed by 10%",
            Display = "Herculean",
            Color = Color3.new(1, 0.91764706373215, 0),
            ControlIncrease = 0.2,
            ProgressSpeedBoost = 10,
            StrokeColor = Color3.new(0.18823529779911, 0.16862745583057, 0)
        },
        Quality = {
            StatIncrease = 0,
            Description = "Increases Luck by 15%, Resilience by 5%, Lure Speed by 15%, & Progress Speed by 5%",
            IsExalted = false,
            Color = Color3.new(0.61960786581039, 1, 0.21568627655506),
            Display = "Quality",
            ProgressSpeedBoost = 5,
            StrokeColor = Color3.new(0.21960784494877, 0.35294118523598, 0.074509806931019)
        },
        Breezed = {
            StatIncrease = 65,
            IsExalted = false,
            Description = "During a windy day, Luck is increased by 65%, Lure Speed by 10%, & Progress Speed by 20%",
            LureSpeedBonus = 10,
            Color = Color3.new(0.73725491762161, 0.81568628549576, 1),
            Display = "Breezed",
            ProgressSpeedBoost = 20,
            StrokeColor = Color3.new(0.10980392247438, 0.1176470592618, 0.14117647707462)
        },
        Hasty = {
            StatIncrease = 55,
            Description = "Increases Lure Speed by 55%",
            Color = Color3.new(0.89803922176361, 0.81960785388947, 0.36078432202339),
            Display = "Hasty",
            IsExalted = false,
            StrokeColor = Color3.new(0.19607843458652, 0.16470588743687, 0.047058824449778)
        },
        Resilient = {
            StatIncrease = 35,
            Description = "Increases Resilience by 35%",
            Color = Color3.new(0.41568627953529, 1, 0.77647060155869),
            Display = "Resilient",
            IsExalted = false,
            StrokeColor = Color3.new(0.066666670143604, 0.11372549086809, 0.098039217293262)
        },
        Blessed = {
            StatIncrease = 5,
            Description = "Increases Shiny & Sparkling chances by 5%, Lure Speed by 5%, & Progress Speed by 5%",
            IsExalted = false,
            Color = Color3.new(1, 0.3098039329052, 0.64313727617264),
            Display = "Blessed",
            ProgressSpeedBoost = 5,
            StrokeColor = Color3.new(0.16470588743687, 0.078431375324726, 0.13333334028721)
        },
        Ghastly = {
            StatIncrease = 100,
            Description = "All caught fish become Translucent, with a 10% chance to double caught fish",
            Color = Color3.new(0.50588238239288, 0.87450981140137, 0.678431391716),
            Display = "Ghastly",
            IsExalted = false,
            StrokeColor = Color3.new(0.1803921610117, 0.3098039329052, 0.2392156869173)
        }
    },
    LoadVisual = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end
}