return {
    Items = {
        ["Windset Totem"] = {
            Rarity = "Rare",
            Price = 2000
        },
        Tidebreaker = {
            Price = 80000,
            OnlyBuyOne = true,
            Rarity = "Mythical"
        },
        ["Hourglass Hull"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Mythical"
        },
        ["Magic Thread"] = {
            Price = math.huge,
            Rarity = "Exotic",
            SellValue = 250
        },
        ["GlimmerSuit Boots"] = {
            Price = math.huge,
            OnlyBuyOne = true,
            Rarity = "Exotic"
        },
        ["Whale Egg Premium"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        ["Faberge Egg"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        ["Timeless Threading"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        ["Mythical Essence"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Mythical"
        },
        ["1000-Year-Old Wood"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        Drill = {
            Price = math.huge,
            OnlyBuyOne = true,
            Rarity = "Exotic"
        },
        ["Basic Diving Gear"] = {
            Price = 3000,
            OnlyBuyOne = true,
            Rarity = "Uncommon"
        },
        ["Crossbow Base"] = {
            Price = math.huge,
            Rarity = "Exotic",
            NonPersistent = true
        },
        ["Megalodon Egg Premium"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        ["Witches Ingredient"] = {
            Rarity = "Rare",
            Price = 10000
        },
        ["Water Bubble"] = {
            Price = 25000,
            OnlyBuyOne = true,
            Rarity = "Legendary"
        },
        ["Smokescreen Totem"] = {
            Rarity = "Rare",
            Price = 2000
        },
        TNT = {
            Price = math.huge,
            purchasable = false,
            Rarity = "Rare"
        },
        ["Zeus Storm Totem"] = {
            Rarity = "Mythical",
            Price = 1500000
        },
        ["Golden Egg Trophy Bobber"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Super Flippers"] = {
            Price = 30000,
            OnlyBuyOne = true,
            Rarity = "Legendary"
        },
        ["Advanced Diving Gear"] = {
            Price = 15000,
            OnlyBuyOne = true,
            Rarity = "Unusual"
        },
        ["Physpax Gun"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        ["Megalodon Egg"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        Windows = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Treasure Map"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Cursed Storm Totem"] = {
            Price = 1000000,
            DataInstanceRequiriment = {
                "Cache.CanPurchaseCursedTotem",
                true,
                "You need to unlock the item before purchasing!"
            },
            Rarity = "Rare"
        },
        ["Sand Of Time"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Legendary"
        },
        GPS = {
            Price = 100,
            OnlyBuyOne = true,
            Rarity = "Uncommon",
            Icon = "rbxassetid://92660360174055"
        },
        ["Eternal Fuel"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Mythical"
        },
        ["Cursed Egg"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        ["Regular Token"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Fish Radar"] = {
            Price = 8000,
            OnlyBuyOne = true,
            Rarity = "Legendary",
            Icon = "rbxassetid://132119413174655"
        },
        ["Hourglass Lantern"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        ["Crossbow Arrow"] = {
            Price = math.huge,
            Rarity = "Exotic",
            NonPersistent = true
        },
        ["Tempest Totem"] = {
            Rarity = "Rare",
            Price = 2000
        },
        ["Ancient Thread"] = {
            Price = math.huge,
            Rarity = "Exotic",
            SellValue = 700
        },
        ["Heart Of Zeus"] = {
            Price = math.huge,
            purchasable = false,
            Rarity = "Mythical"
        },
        ["Consumable XP"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Glimmerfin Suit Lvl 2"] = {
            Price = 7500,
            OnlyBuyOne = true,
            Icon = "rbxassetid://120382468340755",
            Rarity = "Exotic"
        },
        ["Keepers Torch"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        ["Lunar Thread"] = {
            Price = math.huge,
            Rarity = "Exotic",
            SellValue = 1250
        },
        ["Aurora Totem"] = {
            Rarity = "Mythical",
            Price = 500000
        },
        ["Sporey's Soup"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Beginner Oxygen Tank"] = {
            Price = 3500,
            OnlyBuyOne = true,
            Rarity = "Unusual"
        },
        ["Kraken Egg Premium"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        ["Mermaid\xE2\x80\x99s Favor"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Magnifying Glass"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Lava Crystal"] = {
            Price = math.huge,
            Icon = "rbxassetid://94081558964669",
            Rarity = "Exotic"
        },
        ["Ice Crystal"] = {
            Price = math.huge,
            Icon = "rbxassetid://87113404726717",
            Rarity = "Exotic"
        },
        ["Orca Egg Premium"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        ["Eclipse Totem"] = {
            Rarity = "Mythical",
            Price = 250000
        },
        Firework = {
            Rarity = "Limited",
            Price = 130
        },
        ["Back Fins"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Metal Panels"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Cursed Nuke"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Side Fins"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Avalanche Totem"] = {
            Rarity = "Mythical",
            Price = 150000
        },
        ["Conception Conch"] = {
            Rarity = "Mythical",
            Price = 444
        },
        Glider = {
            Price = 900,
            OnlyBuyOne = true,
            Rarity = "Rare"
        },
        ["Skin Crate"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Ethereal Glass"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Mythical"
        },
        ["Blue Moon Totem"] = {
            Rarity = "Rare",
            Price = 500000
        },
        ["Bag of Presents"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Elite Token"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Poseidon Wrath Totem"] = {
            Rarity = "Mythical",
            Price = 1500000
        },
        ["Crossbow Bow"] = {
            Price = math.huge,
            Rarity = "Exotic",
            NonPersistent = true
        },
        ["Crab Cage"] = {
            Rarity = "Unusual",
            Price = 45
        },
        ["Handwritten Note"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        Fillionaire = {
            Rarity = "Exotic",
            Price = math.huge
        },
        Nuke = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Intermediate Oxygen Tank"] = {
            Price = 10000,
            OnlyBuyOne = true,
            Rarity = "Rare"
        },
        Flippers = {
            Price = 9000,
            OnlyBuyOne = true,
            Rarity = "Unusual"
        },
        ["Glimmerfin Suit Lvl 1"] = {
            Price = 7500,
            OnlyBuyOne = true,
            Icon = "rbxassetid://107405457740294",
            Rarity = "Exotic"
        },
        ["Glimmerfin Suit Lvl 3"] = {
            Price = 7500,
            OnlyBuyOne = true,
            Icon = "rbxassetid://137334347694202",
            Rarity = "Exotic"
        },
        ["Winter Cloak"] = {
            Price = 7500,
            OnlyBuyOne = true,
            Rarity = "Unusual"
        },
        ["Silver Egg Trophy Bobber"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Advanced Oxygen Tank"] = {
            Price = 25000,
            OnlyBuyOne = true,
            Rarity = "Legendary"
        },
        Pickaxe = {
            Price = 5000,
            OnlyBuyOne = true,
            Rarity = "Rare"
        },
        ["Meteor Totem"] = {
            Rarity = "Legendary",
            Price = 75000
        },
        ["Basic Oxygen Tank"] = {
            Price = 1000,
            OnlyBuyOne = true,
            Rarity = "Uncommon"
        },
        ["Orca Egg"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        ["Blizzard Totem"] = {
            Rarity = "Mythical",
            Price = 275000
        },
        ["Advanced Glider"] = {
            Price = 2500,
            OnlyBuyOne = true,
            Rarity = "Rare"
        },
        ["Submarine Top"] = {
            Rarity = "Exotic",
            Price = math.huge
        },
        ["Sundial Totem"] = {
            Rarity = "Rare",
            Price = 2000
        },
        ["Whale Egg"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        },
        ["Kraken Egg"] = {
            Price = math.huge,
            Unpurchasable = true,
            Rarity = "Exotic"
        }
    },
    Rarities = {
        "Trash",
        "Common",
        "Uncommon",
        "Unusual",
        "Rare",
        "Legendary",
        "Mythical",
        "Exotic",
        "Secret",
        "Limited",
        "Developer"
    },
    ToInteger = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end,
    RarityColours = {
        Unusual = Color3.new(0.75294119119644, 0.52941179275513, 0.77647060155869),
        Trash = Color3.new(0.5686274766922, 0.5686274766922, 0.5686274766922),
        Common = Color3.new(0.55686277151108, 0.73333334922791, 0.74901962280273),
        Exotic = Color3.new(1, 1, 1),
        Uncommon = Color3.new(0.63137257099152, 1, 0.66274511814117),
        Rare = Color3.new(0.46666666865349, 0.42352941632271, 0.70980393886566),
        Legendary = Color3.new(0.94117647409439, 0.70980393886566, 0.42745098471642),
        Limited = Color3.new(1, 0.50980395078659, 0.22352941334248),
        Extinct = Color3.new(0.21176470816135, 0.28627452254295, 0.6235294342041),
        Relic = Color3.new(0.4705882370472, 1, 0.71764707565308),
        Secret = Color3.new(1, 1, 1),
        Mythical = Color3.new(1, 0.24313725531101, 0.4705882370472)
    },
    ToHex = function() --[[LuaEncode: `options.FunctionsReturnRaw` false; can't serialize functions]] return end
}